### PR TITLE
Complete Issue 2 and add most of the tests of issue #4

### PR DESCRIPTION
**Pull request by map555**

### CODE REVIEW

**Review by sylvainhalle — CHANGES_REQUESTED** [review]
I'd remove the `jdk` line to use the default JDK in Bionic (version 11)

**Review by sylvainhalle — CHANGES_REQUESTED** [review]
I would separate the test so that one verifies `AffineTransformFloat`, the other `AffineTransformInteger`, etc. It is better to have multiple small tests that each verify one thing, than one big test that verifies lots of things at the same time.

**Comment by map555** [comment]
> 
> 
> I'd remove the `jdk` line to use the default JDK in Bionic (version 11)

I fixed it.

**Comment by map555** [comment]
> 
> 
> I would separate the test so that one verifies `AffineTransformFloat`, the other `AffineTransformInteger`, etc. It is better to have multiple small tests that each verify one thing, than one big test that verifies lots of things at the same time.

I fixed it too.

**Pull request merged**
